wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.12
    start_time: 1697226785.081844
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.10.12
      5: 0.13.10
      8:
      - 5
batch-size:
  desc: null
  value: 8
dropout:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 10
metric:
  desc: null
  value: accuracy
